---
title: "NASDAQ"
output:
  html_document:
    df_print: paged
  word_document: default
  pdf_document: default
---

```{r}
library(tidyverse)
library(tseries)
library(strucchange)
library(ARDL)
library(car)
library(readxl)
```

```{r}
library(readxl)
selected_data <- read_excel("FYP data\\log_level data\\ixichkd_log_level_clean.xlsx")

```

```{r}
selected_data <- na.omit(selected_data)
head(selected_data)
```

```{r}
summary(selected_data)
```

```{r}
# The first step is to run ADF test as ARDL does not allow I(2) Stationary
test_stationarity <- function(x, name) {
  cat("\n=== ", name, " ===\n")
  cat("ADF test (levels):\n")
  print(adf.test(x, alternative = "stationary"))
  
  cat("\nADF test (first difference):\n")
  print(adf.test(diff(x), alternative = "stationary"))
}

```

```{r}
test_stationarity(selected_data$cpi_month, "CPI Inflation")
```
CPI inflation is I(1) Stationary

```{r}
test_stationarity(selected_data$log_price, "Log Price")
```

Log Nasdaq is I(1) Stationary


```{r}
# Bai Perron Method to Search for Breakpoints
bp_cpi <- breakpoints(log_price ~ cpi_month, data = selected_data, h = 0.15, breaks = 5)
summary(bp_cpi)
```


```{r}
# Breakpoint extraction
breakpoints <- c(107,224,365)
n <- nrow(selected_data)
n_regimes <- length(breakpoints) + 1
print(length(breakpoints))
regime <- cut(1:n, 
              breaks = c(0, breakpoints, n), 
              labels = FALSE)

# Create dummy variables for each regime (excluding one as reference if needed)
for(i in 1:n_regimes) {
  selected_data[[paste0("regime_", i)]] <- ifelse(regime == i, 1, 0)
}

# Check the dummies
head(selected_data,10)

```


```{r}
# Run estimation and pick the best model. Maximum lags allowed are 12.
# add all regimes except regime_1
best_models <- auto_ardl(log_price ~ cpi_month| regime_2+ regime_3+ regime_4,
              data = selected_data,
              max_order = c(12,12),   # max lags for stock_return and cpi_inflation
              selection = "AIC",# use AIC for lag selection
              ) 
best_models$top_orders
# We pick the best model that is not (x,0)
p <- best_models$top_orders[4, 1]
q <- best_models$top_orders[4, 2]
best_ardl_model <- ardl(log_price ~ cpi_month | regime_2+ regime_3+ regime_4,
                  data = selected_data,
                   order = c(p, q))
summary(best_ardl_model)

```


```{r}
# Perform the bounds F-test for cointegration
bounds_test_result <- bounds_f_test(best_ardl_model, case = 3)

# Print the results
print(bounds_test_result)
```
Since F is greater than 5.73, NASDAQ is cointegrated with CPI.

```{r}
# Extract the Long-Run coefficients
multi_lr <- multipliers(best_ardl_model)
print(multi_lr)

library(car)
# perform wald test/test fisher hypothesis
uecm_model <- uecm(best_ardl_model)
names(coef(uecm_model))
fisher_test <- linearHypothesis(uecm_model, "L(cpi_month, 1) + L(log_price, 1) = 0")
print(fisher_test)
```
Long-run Beta : 3.406828
p_value testing Beta=0 : 9.114770e-13
p_value testing Beta=1: 0.0005048

```{r}
# Lastly, get the short run dynamics
ecm_results <- recm(best_ardl_model, case = 3)
summary(ecm_results)
```


```{r}
# Model Diagnostics
# 1. Serial Correlation (Breusch-Godfrey)
lmtest::bgtest(ecm_results)

# 2. Heteroskedasticity (Breusch-Pagan)
lmtest::bptest(ecm_results)

# 3. Normality (Jarque-Bera)
tseries::jarque.bera.test(residuals(ecm_results))
```


